name: Slither Analysis
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  analyze:
    runs-on: ubuntu-latest
    name: Slither Security Analysis
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - uses: crytic/slither-action@v0.3.0
        name: Run Slither
        id: slither
        with:
          node-version: 16
          sarif: results.sarif
          fail-on: none

      - uses: github/codeql-action/upload-sarif@v2
        name: Upload SARIF file
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
