name: unit-test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Hardhat Unit Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Environment
        uses: actions/setup-node@v3
      - name: Test
        uses: ambersun1234/hardhat-test-action@v1
        with:
          network: hardhat
